characters: tuple[str, ...] = (
    "gd_assassin_streaming_sf",
    "gd_mercenary_streaming_sf",
    "gd_siren_streaming_sf",
    "gd_soldier_streaming_sf",
    "gd_tulip_mechro_streaming_sf",
    "gd_lilac_psycho_streaming_sf",
)

levels: tuple[tuple[str, ...], ...] = (
    #fmt: off
    ("GD_Globals.General.LevelList",                       "Arid Nexus - Boneyard",          "Fyrestone_P",            'Fyrestone_Combat', 'Fyrestone_Dynamic', 'Fyrestone_Audio', 'Fyrestone_FX', 'Fyrestone_Light'),
    ("GD_Globals.General.LevelList",                       "The Holy Spirits",               "Luckys_P",               'Luckys_Light', 'Luckys_FX', 'Luckys_Audio', 'Luckys_Dynamic'),
    ("GD_Globals.General.LevelList",                       "Southpaw Steam & Power",         "SouthpawFactory_P",      'SouthpawFactory_Light', 'SouthpawFactory_Dynamic', 'SouthpawFactory_Audio'),
    ("GD_Globals.General.LevelList",                       "Sanctuary Hole",                 "Sanctuary_Hole_P",       'Sanctuary_Hole_Audio', 'Sanctuary_Hole_Combat', 'Sanctuary_Hole_Dynamic', 'Sanctuary_Hole_FX', 'Sanctuary_Hole_Light', 'Sanctuary_Hole_Skybox'),
    ("GD_Globals.General.LevelList",                       "Hero's Pass",                    "FinalBossAscent_P",      'FinalBossAscent_Combat', 'FinalBossAscent_Dynamic', 'FinalBossAscent_Skybox', 'FinalBossAscent_Audio', 'FinalBossAscent_FX', 'FinalBossAscent_Light'),
    ("GD_Globals.General.LevelList",                       "Bloodshot Stronghold",           "dam_p",                  'Dam_Audio', 'Dam_Combat', 'Dam_Dynamic', 'Dam_FX'),
    ("GD_Globals.General.LevelList",                       "Three Horns - Valley",           "Frost_P",                'Frost_Audio', 'Frost_Dynamic', 'Frost_FX', 'Frost_Light'),
    ("GD_Globals.General.LevelList",                       "Sanctuary",                      "Sanctuary_P",            'Sanctuary_Light', 'Sanctuary_Audio', 'Sanctuary_FX', 'Sanctuary_Dynamic', 'Sanctuary_Combat', 'Sanctuary_Land', 'Sanctuary_Outer', 'Sanctuary_Side'),
    ("GD_Globals.General.LevelList",                       "Thousand Cuts",                  "Grass_Cliffs_P",         'Grass_Cliffs_Dynamic', 'Grass_Cliffs_Combat', 'Grass_Cliffs_FX', 'Grass_Cliffs_Audio', 'Grass_Cliffs_Light'),
    ("GD_Globals.General.LevelList",                       "End of the Line",                "TundraTrain_P",          'TundraTrain_Audio', 'TundraTrain_Combat', 'TundraTrain_Dynamic', 'TundraTrain_FX', 'TundraTrain_Light'),
    ("GD_Globals.General.LevelList",                       "Wildlife Exploitation Preserve", "PandoraPark_P",          'PandoraPark_Audio', 'PandoraPark_Combat', 'PandoraPark_Light', 'PandoraPark_Dynamic', 'PandoraPark_Bloodwing'),
    ("GD_Globals.General.LevelList",                       "Terramorphous Peak",             "ThresherRaid_P",         'ThresherRaid_Light', 'ThresherRaid_Audio', 'ThresherRaid_FX', 'ThresherRaid_Dynamic', 'ThresherRaid_Combat'),
    ("GD_Globals.General.LevelList",                       "Tundra Express",                 "tundraexpress_p",        'TundraExpress_Light', 'TundraExpress_Audio', 'TundraExpress_Combat', 'TundraExpress_Dynamic', 'TundraExpress_FX'),
    ("GD_Globals.General.LevelList",                       "The Fridge",                     "Fridge_P",               'Fridge_Audio', 'Fridge_Caves', 'Fridge_Light', 'Fridge_Combat', 'Fridge_Dynamic', 'Fridge_FX', 'Fridge_Skybox'),
    ("GD_Globals.General.LevelList",                       "Southern Shelf - Bay",           "Cove_P",                 'Cove_Audio', 'Cove_Dynamic', 'Cove_FX', 'Cove_LiarsBerg', 'Cove_Skybox', 'Cove_Light'),
    ("GD_Globals.General.LevelList",                       "Frostburn Canyon",               "icecanyon_p",            'IceCanyon_Light', 'IceCanyon_Audio', 'IceCanyon_Dynamic', 'IceCanyon_FX', 'IceCanyon_Combat'),
    ("GD_Globals.General.LevelList",                       "Fink's Slaughterhouse",          "BanditSlaughter_P",      'BanditSlaughter_Light', 'BanditSlaughter_FX', 'BanditSlaughter_Audio', 'BanditSlaughter_Dynamic', 'BanditSlaughter_Skybox', 'BanditSlaughter_Combat'),
    ("GD_Globals.General.LevelList",                       "Three Horns - Divide",           "Ice_P",                  'Ice_Light', 'Ice_Dynamic', 'Ice_Audio', 'Ice_FX'),
    ("GD_Globals.General.LevelList",                       "The Highlands",                  "Grass_P",                'Grass_Dynamic', 'Grass_Dam', 'Grass_Audio', 'Grass_Light', 'Grass_Combat'),
    ("GD_Globals.General.LevelList",                       "Natural Selection Annex",        "CreatureSlaughter_P",    'CreatureSlaughter_Light', 'CreatureSlaughter_FX', 'CreatureSlaughter_Audio', 'CreatureSlaughter_Dynamic', 'CreatureSlaughter_Skybox', 'CreatureSlaughter_Combat'),
    ("GD_Globals.General.LevelList",                       "The Dust",                       "Interlude_P",            'Interlude_Light', 'Interlude_Audio', 'Interlude_Dynamic', 'Interlude_Combat', 'Interlude_FX', 'Interlude_Skybox'),
    ("GD_Globals.General.LevelList",                       "Opportunity",                    "HyperionCity_P",         'HyperionCity_Skybox', 'HyperionCity_Light', 'HyperionCity_Audio', 'HyperionCity_FX', 'HyperionCity_Combat', 'HyperionCity_Dynamic'),
    ("GD_Globals.General.LevelList",                       "Bloodshot Ramparts",             "damtop_p",               'DamTop_Skybox', 'DamTop_Light', 'DamTop_Combat', 'DamTop_Dynamic', 'DamTop_FX', 'DamTop_Audio'),
    ("GD_Globals.General.LevelList",                       "Control Core Angel",             "VOGChamber_P",           'VOGChamber_Audio', 'VOGChamber_Combat', 'VOGChamber_Dynamic', 'VOGChamber_SanctuaryRoom', 'VOGChamber_FX', 'VOGChamber_Light', 'VOGChamber_Skybox'),
    ("GD_Globals.General.LevelList",                       "Sanctuary",                      "SanctuaryAir_P",         'SanctuaryAir_Audio', 'SanctuaryAir_Combat', 'SanctuaryAir_Dynamic', 'SanctuaryAir_FX', 'SanctuaryAir_Light', 'SanctuaryAir_Side'),
    ("GD_Globals.General.LevelList",                       "Ore Chasm",                      "RobotSlaughter_P",       'RobotSlaughter_Light', 'RobotSlaughter_FX', 'RobotSlaughter_Audio', 'RobotSlaughter_Dynamic', 'RobotSlaughter_Skybox'),
    ("GD_Globals.General.LevelList",                       "Arid Nexus - Badlands",          "Stockade_P",             'Stockade_Audio', 'Stockade_Combat', 'Stockade_Dynamic', 'Stockade_FX', 'Stockade_Light'),
    ("GD_Globals.General.LevelList",                       "Southern Shelf",                 "SouthernShelf_P",        'SouthernShelf_Audio', 'SouthernShelf_Combat', 'SouthernShelf_Dynamic', 'SouthernShelf_Freighter', 'SouthernShelf_FX', 'SouthernShelf_LiarsBerg', 'SouthernShelf_Light', 'SouthernShelf_Skybox', 'SouthernShelf_Tundra'),
    ("GD_Globals.General.LevelList",                       "The Highlands - Outwash",        "Outwash_P",              'Outwash_Light', 'Outwash_Dynamic', 'Outwash_Dam', 'Outwash_Combat', 'Outwash_Audio'),
    ("GD_Globals.General.LevelList",                       "Sawtooth Cauldron",              "CraterLake_P",           'CraterLake_Light', 'CraterLake_Combat', 'CraterLake_Dynamic', 'CraterLake_FX', 'CraterLake_Audio'),
    ("GD_Globals.General.LevelList",                       "Friendship Gulag",               "HypInterlude_P",         'HypInterlude_Dynamic', 'HypInterlude_Light', 'HypInterlude_Audio'),
    ("GD_Globals.General.LevelList",                       "Caustic Caverns",                "caverns_p",              'Caverns_Top', 'Caverns_Audio', 'Caverns_Combat', 'Caverns_Dynamic', 'Caverns_FX', 'Caverns_Light', 'Caverns_Skybox'),
    ("GD_Globals.General.LevelList",                       "Lynchwood",                      "Grass_Lynchwood_P",      'Grass_Lynchwood_Audio', 'Grass_Lynchwood_Combat', 'Grass_Lynchwood_Dynamic', 'Grass_Lynchwood_FX', 'Grass_Lynchwood_Light'),
    ("GD_Globals.General.LevelList",                       "Windshear Waste",                "Glacial_P",              'Glacial_Light', 'Glacial_Skybox', 'Glacial_Audio', 'Glacial_FX', 'Glacial_Dynamic', 'Glacial_Tundra'),
    ("GD_Globals.General.LevelList",                       "The Bunker",                     "Boss_Cliffs_P",          'Boss_Cliffs_Dynamic', 'Boss_Cliffs_Combat', 'Boss_Cliffs_CombatLoader', 'Boss_Cliffs_Audio', 'Boss_Cliffs_FX', 'Boss_Cliffs_Light', 'Boss_Cliffs_Skybox', 'Boss_Cliffs_Skybox_Grass', 'Boss_Cliffs_VOGAntechamber'),
    ("GD_Globals.General.LevelList",                       "Vault of the Warrior",           "Boss_Volcano_P",         'Boss_Volcano_Dynamic', 'Boss_Volcano_Combat', 'Boss_Volcano_Audio', 'Boss_Volcano_FX', 'Boss_Volcano_Light', 'Boss_Volcano_Skybox', 'Boss_Volcano_Combat_Monster', 'Boss_Volcano_Cutscenes'),
    ("GD_Globals.General.LevelList",                       "Eridium Blight",                 "Ash_P",                  'Ash_Light', 'Ash_Combat', 'Ash_Dynamic', 'Ash_FX', 'Ash_Audio'),
    ("GD_AlliumPackageDef.AlliumTG_LevelList",             "Gluttony Gulch",                 "Hunger_P",               'HUNGER_AUDIO', 'Hunger_Dynamic', 'Hunger_Boss', 'Hunger_Mission_1', 'Hunger_Mission_2', 'Hunger_Mission_3', 'Hunger_Mission_Intro', 'Hunger_Machinery'),
    ("GD_AlliumPackageDef.AlliumXmas_LevelList",           "Frost Bottom",                   "Xmas_P",                 'Xmas_Audio', 'Xmas_Combat', 'Xmas_Dynamic', 'XMas_Light', 'Xmas_Skybox', 'Xmas_Boss', 'Xmas_Mission'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Helios Fallen",                  "Helios_P",               'Helios_Audio', 'Helios_Light', 'Helios_Skybox', 'Helios_VFX', 'Helios_Mission_Main', 'Helios_Mission_Side', 'Helios_LD', 'Helios_Interactive', 'Helios_MoonshotCannon', 'Helios_UranusArena', 'Helios_Landscape', 'Helios_Floor1', 'Helios_LaserControlRoom', 'Helios_SideA', 'Helios_RobotFactory', 'Helios_SniperArea', 'Helios_MoxxiArea', 'Helios_HangarSpaceShips', 'Helios_Warehouse_Rockets', 'Helios_DahlMine_Before', 'Helios_DahlMine_After', 'Helios_Toggle_Sanctuary'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Paradise Sanctum",               "GaiusSanctuary_P",       'GaiusSanctuary_Audio', 'GaiusSanctuary_Light', 'GaiusSanctuary_Cinema', 'GaiusSanctuary_SkyBox', 'GaiusSanctuary_VFX', 'GaiusSanctuary_MissionMain', 'GaiusSanctuary_MissionSide', 'GaiusSanctuary_Nav', 'GaiusSanctuary_Interactive', 'GaiusSanctuary_Moxxi', 'GaiusSanctuary_Scooter', 'GaiusSanctuary_Boss', 'GaiusSanctuary_Catwalk', 'GaiusSanctuary_MarcusHQ', 'GaiusSanctuary_Reactor'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "The Backburner",                 "BackBurner_P",           'BackBurner_Landscape', 'BackBurner_Mountain', 'BackBurner_Skybox', 'BackBurner_VFX', 'BackBurner_Audio', 'BackBurner_Light', 'BackBurner_Camp', 'BackBurner_LD', 'BackBUrner_Mission_Main', 'BackBurnerInteractive', 'BackBurner_Mission_Side', 'BackBurner_Toggle_Brick_ON', 'BackBurner_Toggle_Brick_OFF', 'BackBurner_Toggle_Moxxi_ON', 'BackBurner_Toggle_Moxxi_OFF', 'BackBurner_Toggle_Ellie_ON', 'BackBurner_Toggle_Ellie_OFF', 'BackBurner_Toggle_Tina_ON', 'BackBurner_Toggle_Tina_OFF', 'BackBurner_Toggle_Mordecai_ON', 'BackBurner_Toggle_Mordecai_OFF', 'BackBurner_Toggle_Zed_ON', 'BackBurner_Toggle_Zed_OFF', 'BackBurner_Toggle_Marcus_ON', 'BackBurner_Toggle_Marcus_OFF', 'BackBurner_Toggle_Claptrap_ON'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Fight for Sanctuary",            "SanctIntro_P",           'SANCTINTRO_AUDIO', 'SanctIntro_Cinema', 'SanctIntro_Combat', 'SanctIntro_Dynamic', 'SanctIntro_Interactive', 'SanctIntro_Light', 'SanctIntro_Loot', 'SanctIntro_MissionMain', 'SanctIntro_MissionSide', 'SanctIntro_Nav', 'SanctIntro_SkyBox', 'SanctIntro_VFX', 'SanctIntro_Infection'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Dahl Abandon",                   "OldDust_P",              'OldDust_Audio', 'OldDust_Light', 'OldDust_Skybox', 'OldDust_VFX', 'OldDust_Mission_Main', 'OldDust_Mission_Side', 'OldDust_LD', 'OldDust_Interactive', 'OldDust_Backburner', 'OldDust_Mountain', 'OldDust_SandwormEntrance', 'OldDust_Lair', 'OldDust_Landscape', 'OldDust_Approach', 'OldDust_DahlDoorBefore', 'OldDust_DahlDoorAfter', 'OldDust_Sanctuary_Before', 'OldDust_Sanctuary_After'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Mt. Scarab Research Center",     "ResearchCenter_P",       'ResearchCenter_Audio', 'ResearchCenter_Cinema', 'ResearchCenter_Light', 'ResearchCenter_SkyBox', 'ResearchCenter_VFX', 'ResearchCenter_MissionSide', 'ResearchCenter_MissionMain', 'ResearchCenter_Interactive', 'ResearchCenter_Nav', 'ResearchCenter_Entrance', 'ResearchCenter_Lift', 'ResearchCenter_Dev', 'ResearchCenter_Research', 'ResearchCenter_Boss', 'ResearchCenter_Exterior', 'ResearchCenter_Prison'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "Writhing Deep",                  "SandwormLair_P",         'SandwormLair_Terrain', 'SandwormLair_GD', 'SandwormLair_VFX', 'SandwormLair_Audio', 'SandwormLair_LD', 'SandwormLair_Light'),
    ("GD_AnemonePackageDef.Anemone_LevelList",             "The Burrows",                    "Sandworm_P",             'Sandworm_Light', 'Sandworm_Skybox', 'Sandworm_Audio', 'Sandworm_VFX', 'Sandworm_Mission_Main', 'Sandworm_Mission_Side', 'Sandworm_Interactive', 'Sandworm_Side_HypoOathPart2', 'Sandworm_Encounters', 'Sandworm_Landscape', 'Sandworm_Tunnel', 'Sandworm_Zone_01', 'Sandworm_Zone_02', 'Sandworm_Zone_03', 'Sandworm_Zone_04', 'Sandworm_Zone_05'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "The Forest",                     "Dark_Forest_P",          'Dark_Forest_Audio', 'Dark_Forest_Combat', 'Dark_Forest_Dynamic', 'Dark_Forest_FX', 'Dark_Forest_Light', 'Dark_Forest_Skybox', 'Dark_Forest_Missions'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Immortal Woods",                 "Dead_Forest_P",          'Dead_Forest_Audio', 'Dead_Forest_Combat', 'Dead_Forest_Dynamic', 'Dead_Forest_FX', 'Dead_Forest_Light', 'Dead_Forest_Skybox', 'Dead_Forest_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Dragon Keep",                    "CastleKeep_P",           'CastleKeep_Audio', 'CastleKeep_Combat', 'CastleKeep_Dynamic', 'CastleKeep_FX', 'CastleKeep_Light', 'CastleKeep_Skybox', 'CastleKeep_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Unassuming Docks",               "Docks_P",                'Docks_Audio', 'Docks_Combat', 'Docks_Dynamic', 'Docks_FX', 'DOCKS_LIGHT', 'Docks_Skybox', 'Docks_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Flamerock Refuge",               "Village_P",              'Village_Audio', 'Village_Dynamic', 'Village_FX', 'Village_Light', 'Village_Skybox', 'Village_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Hatred's Shadow",                "CastleExterior_P",       'CastleExterior_Audio', 'CastleExterior_Combat', 'CastleExterior_Dynamic', 'CastleExterior_FX', 'CastleExterior_Light', 'CastleExterior_Skybox', 'CastleExterior_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Lair of Infinite Agony",         "Dungeon_P",              'Dungeon_Audio', 'Dungeon_Combat', 'Dungeon_Dynamic', 'Dungeon_FX', 'Dungeon_Light', 'Dungeon_Skybox', 'Dungeon_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Murderlin's Temple",             "TempleSlaughter_P",      'TempleSlaughter_Audio', 'TempleSlaughter_Combat', 'TempleSlaughter_Light'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "Mines of Avarice",               "Mines_P",                'Mines_Audio', 'Mines_Combat', 'Mines_Dynamic', 'Mines_FX', 'Mines_Light', 'Mines_Skybox', 'Mines_Mission'),
    ("GD_AsterPackageDef.Aster_LevelList",                 "The Winged Storm",               "DungeonRaid_P",          'DungeonRaid_Audio', 'DungeonRaid_Combat', 'DungeonRaid_Dynamic', 'DungeonRaid_FX', 'DungeonRaid_Light', 'DungeonRaid_Skybox'),
    ("GD_FlaxPackageDef.Flax_LevelList",                   "Hallowed Hollow",                "Pumpkin_Patch_P",        'PUMPKIN_PATCH_COMBAT', 'PUMPKIN_PATCH_AUDIO', 'Pumpkin_Patch_Dynamic', 'Pumpkin_Patch_FX', 'Pumpkin_Patch_Boss'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "The Beatdown",                   "Iris_DL2_P",             'Iris_DL2_Audio', 'Iris_DL2_Combat', 'Iris_DL2_Dynamic', 'Iris_DL2_FX', 'Iris_DL2_Light', 'Iris_DL2_Skybox'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Southern Raceway",               "Iris_Hub2_P",            'Iris_Hub2_Audio', 'Iris_Hub2_Colosseum', 'Iris_Hub2_Combat', 'Iris_Hub2_Dynamic', 'Iris_Hub2_FX', 'Iris_Hub2_Light', 'Iris_Hub2_Raid', 'Iris_Hub2_Skybox'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Badass Crater of Badassitude",   "Iris_Hub_P",             'IRIS_HUB_SKYBOX', 'Iris_Hub_Light', 'Iris_Hub_Colosseum', 'Iris_Hub_Audio', 'Iris_Hub_Combat', 'Iris_Hub_Dynamic', 'Iris_Hub_FX', 'Iris_Hub_Race'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Arena",                          "Iris_DL1_TAS_P",         'Iris_DL1_TAS_Audio', 'Iris_DL1_TAS_Combat', 'Iris_DL1_TAS_Dynamic', 'Iris_DL1_TAS_FX', 'Iris_DL1_TAS_Light', 'Iris_DL1_TAS_Skybox'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Pyro Pete's Bar",                "Iris_DL2_Interior_P",    'Iris_DL2_Interior_Audio', 'Iris_DL2_Interior_Combat', 'Iris_DL2_Interior_Dynamic', 'Iris_DL2_Interior_Light', 'Iris_DL2_Interior_Raid'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Arena",                          "Iris_DL1_P",             'Iris_DL1_Audio', 'Iris_DL1_Battle', 'Iris_DL1_Combat', 'Iris_DL1_Dynamic', 'Iris_DL1_FX', 'Iris_DL1_Light', 'Iris_DL1_Skybox'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Badass Crater Bar",              "Iris_Moxxi_P",           'Iris_Moxxi_Audio'),
    ("GD_IrisPackageDef.LevelList.Iris_LevelList",         "Forge",                          "Iris_DL3_P",             'Iris_DL3_Light', 'Iris_DL3_Dynamic', 'Iris_DL3_Combat', 'Iris_DL3_Audio', 'Iris_DL3_FX', 'Iris_DL3_Skybox'),
    ("GD_LobeliaPackageDef.LevelList",                     "The Raid on Digistruct Peak",    "TestingZone_P",          'TESTINGZONE_LIGHT', 'TESTINGZONE_COMBAT', 'TestingZone_Audio'),
    ("GD_NasturtiumPackageDef.NasturtiumEaster_LevelList", "Wam Bam Island",                 "Easter_P",               'Easter_Audio', 'Easter_Boss', 'Easter_Combat', 'Easter_Dynamic', 'Easter_FX', 'Easter_Lights', 'Easter_Mission', 'Easter_Mission_1', 'Easter_Mission_2', 'Easter_Mission_Side', 'Easter_Skybox'),
    ("GD_NasturtiumPackageDef.NasturtiumVday_LevelList",   "Rotgut Distillery",              "Distillery_P",           'Distillery_Audio', 'Distillery_Boss', 'Distillery_Dynamic', 'Distillery_Combat', 'Distillery_FX', 'Distillery_IntroOutro', 'DISTILLERY_LIGHT2', 'Distillery_Mission', 'Distillery_Mission2', 'Distillery_Mission3', 'Distillery_Side_Mission', 'Distillery_Skybox'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "The Leviathan's Lair",           "Orchid_WormBelly_P",     'Orchid_WormBelly_Audio', 'Orchid_WormBelly_Dynamic', 'Orchid_WormBelly_FX', 'Orchid_WormBelly_Light'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "Washburne Refinery",             "Orchid_Refinery_P",      'Orchid_Refinery_Combat', 'Orchid_Refinery_Dynamic', 'Orchid_Refinery_Light', 'Orchid_Refinery_Raid', 'Orchid_Refinery_Audio'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "Wurmwater",                      "Orchid_SaltFlats_P",     'Orchid_SaltFlats_Audio', 'Orchid_SaltFlats_Combat', 'Orchid_SaltFlats_Dynamic', 'Orchid_SaltFlats_FX', 'Orchid_SaltFlats_Light', 'Orchid_SaltFlats_Race', 'Orchid_SaltFlats_Refinery', 'Orchid_SaltFlats_Ship', 'Orchid_SaltFlats_Skybox'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "Oasis",                          "Orchid_OasisTown_P",     'Orchid_OasisTown_Combat', 'Orchid_OasisTown_Dynamic', 'Orchid_OasisTown_Light', 'Orchid_OasisTown_Skybox', 'Orchid_OasisTown_Audio'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "Magnys Lighthouse",              "Orchid_Spire_P",         'Orchid_Spire_Audio', 'Orchid_Spire_Combat', 'Orchid_Spire_Dynamic', 'Orchid_Spire_FX', 'Orchid_Spire_Light', 'Orchid_Spire_Skybox'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "The Rustyards",                  "Orchid_ShipGraveyard_P", 'Orchid_ShipGraveyard_Combat', 'Orchid_ShipGraveyard_Dynamic', 'Orchid_ShipGraveyard_Light', 'Orchid_ShipGraveyard_Audio', 'Orchid_ShipGraveyard_Skybox'),
    ("GD_OrchidPackageDef.LevelList.Orchid_LevelList",     "Hayter's Folly",                 "Orchid_Caves_P",         'Orchid_Caves_Audio', 'Orchid_Caves_Combat', 'ORCHID_CAVES_DYNAMIC', 'Orchid_Caves_FX', 'ORCHID_CAVES_LIGHT', 'Orchid_Caves_Raid_C', 'Orchid_Caves_Raid_P', 'ORCHID_CAVES_SKYBOX'),
    ("GD_SagePackageDef.LevelList.Sage_LevelList",         "Ardorton Station",               "Sage_PowerStation_P",    'Sage_PowerStation_Audio', 'Sage_PowerStation_Combat', 'Sage_PowerStation_Dynamic', 'Sage_PowerStation_FX', 'Sage_PowerStation_Light', 'Sage_PowerStation_Skybox'),
    ("GD_SagePackageDef.LevelList.Sage_LevelList",         "Hunter's Grotto",                "Sage_Underground_P",     'Sage_Underground_Audio', 'Sage_Underground_Combat', 'Sage_Underground_Dynamic', 'Sage_Underground_Light'),
    ("GD_SagePackageDef.LevelList.Sage_LevelList",         "Candlerakk's Crag",              "Sage_Cliffs_P",          'Sage_Cliffs_Audio', 'SAGE_CLIFFS_COMBAT', 'Sage_Cliffs_Dynamic', 'SAGE_CLIFFS_LIGHT', 'SAGE_CLIFFS_SKYBOX', 'Sage_Cliffs_Raid'),
    ("GD_SagePackageDef.LevelList.Sage_LevelList",         "H.S.S. Terminus",                "Sage_HyperionShip_P",    'Sage_HyperionShip_Audio', 'Sage_HyperionShip_Dynamic', 'Sage_HyperionShip_Light'),
    ("GD_SagePackageDef.LevelList.Sage_LevelList",         "Scylla's Grove",                 "Sage_RockForest_P",      'Sage_RockForest_Audio', 'Sage_RockForest_Combat', 'Sage_RockForest_Dynamic', 'Sage_RockForest_FX', 'Sage_RockForest_Light', 'Sage_RockForest_Skybox'),
    #fmt: on
)

package_sizes: dict[str, int] = {
    "ash_combat": 38068224,
    "ash_dynamic": 14589952,
    "ash_p": 78561280,
    "ash_px": 73945088,
    "backburner_camp": 30773248,
    "backburner_cinematic": 131244032,
    "backburner_landscape": 3383296,
    "backburner_ld": 1298432,
    "backburner_mission_main": 14168064,
    "backburner_mission_side": 2347008,
    "backburner_p": 17612800,
    "backburner_skybox": 1630208,
    "backburner_toggle_brick_on": 1073152,
    "backburner_toggle_moxxi_on": 1699840,
    "backburner_toggle_tina_on": 1409024,
    "backburner_toggle_zed_on": 2228224,
    "backburner_vfx": 557056,
    "backburnerinteractive": 1531904,
    "banditslaughter_combat": 13316096,
    "banditslaughter_p": 6680576,
    "benchmark_px": 2207744,
    "benchmark": 53587968,
    "boss_cliffs_combat": 3579904,
    "boss_cliffs_combatloader": 3452928,
    "boss_cliffs_dynamic": 4714496,
    "boss_cliffs_p": 11386880,
    "boss_cliffs_skybox_grass": 3821568,
    "boss_cliffs_skybox": 4743168,
    "boss_cliffs_vogantechamber": 2641920,
    "boss_volcano_combat_monster": 15032320,
    "boss_volcano_combat": 6279168,
    "boss_volcano_cutscenes": 10797056,
    "boss_volcano_fx": 1462272,
    "boss_volcano_p": 30064640,
    "castleexterior_combat": 11186176,
    "castleexterior_light": 901120,
    "castleexterior_mission": 8630272,
    "castleexterior_p": 25264128,
    "castleexterior_px": 1601536,
    "castleexterior_skybox": 585728,
    "castlekeep_combat": 5951488,
    "castlekeep_dynamic": 4673536,
    "castlekeep_light": 1605632,
    "castlekeep_mission": 11436032,
    "castlekeep_p": 5505024,
    "castlekeep_skybox": 1572864,
    "caverns_dynamic": 589824,
    "caverns_fx": 1101824,
    "caverns_p": 56676352,
    "caverns_px": 978944,
    "cd_assassin_skin_yellowa_sf": 5083136,
    "cd_bandittech_skin_bluedk_sf": 679936,
    "cd_bandittech_skin_effer_sf": 1540096,
    "cd_hovercraft_skin_blue_sf": 991232,
    "cd_hovercraft_skin_bluedk_sf": 618496,
    "cd_hovercraft_skin_greendk_sf": 663552,
    "cd_psycho_skin_vladofc_sf": 5079040,
    "cove_dynamic": 5144576,
    "cove_liarsberg": 1146880,
    "cove_p": 61861888,
    "cove_px": 679936,
    "craterlake_combat": 21327872,
    "craterlake_dynamic": 2719744,
    "craterlake_p": 37195776,
    "craterlake_px": 77959168,
    "creatureslaughter_dynamic": 18653184,
    "creatureslaughter_p": 19398656,
    "creatureslaughter_px": 2564096,
    "creatureslaughter_skybox": 1486848,
    "dam_combat": 10215424,
    "dam_dynamic": 11153408,
    "dam_p": 26996736,
    "dam_px": 1712128,
    "damtop_combat": 19742720,
    "damtop_dynamic": 5156864,
    "damtop_p": 26841088,
    "damtop_px": 1720320,
    "damtop_skybox": 2555904,
    "dark_forest_combat": 5804032,
    "dark_forest_dynamic": 3923968,
    "dark_forest_fx": 1196032,
    "dark_forest_missions": 11771904,
    "dark_forest_p": 19189760,
    "dark_forest_px": 659456,
    "dark_forest_skybox": 942080,
    "dead_forest_combat": 4579328,
    "dead_forest_dynamic": 1159168,
    "dead_forest_fx": 1503232,
    "dead_forest_mission": 16162816,
    "dead_forest_p": 14671872,
    "distillery_boss": 6918144,
    "distillery_combat": 925696,
    "distillery_dynamic": 2236416,
    "distillery_introoutro": 3481600,
    "distillery_light2": 1224704,
    "distillery_mission": 8867840,
    "distillery_mission2": 3067904,
    "distillery_mission3": 8699904,
    "distillery_p": 18538496,
    "distillery_side_mission": 5316608,
    "distillery_skybox": 2740224,
    "docks_combat": 4239360,
    "docks_light": 675840,
    "docks_mission": 3833856,
    "docks_p": 24371200,
    "dungeon_combat": 8126464,
    "dungeon_mission": 7090176,
    "dungeon_p": 13180928,
    "dungeonraid_combat": 4710400,
    "dungeonraid_dynamic": 1323008,
    "dungeonraid_p": 6791168,
    "dungeonraid_skybox": 712704,
    "easter_boss": 6176768,
    "easter_combat": 7831552,
    "easter_dynamic": 3645440,
    "easter_fx": 1593344,
    "easter_mission_1": 3645440,
    "easter_mission_2": 5042176,
    "easter_mission_side": 3633152,
    "easter_mission": 1146880,
    "easter_p": 23793664,
    "easter_skybox": 802816,
    "finalbossascent_combat": 31240192,
    "finalbossascent_dynamic": 5378048,
    "finalbossascent_p": 38526976,
    "finalbossascent_px": 1110016,
    "finalbossascent_skybox": 4308992,
    "fridge_combat": 8724480,
    "fridge_dynamic": 4395008,
    "fridge_light": 610304,
    "fridge_p": 28684288,
    "fridge_px": 3465216,
    "frost_dynamic": 18653184,
    "frost_p": 57106432,
    "frost_px": 528384,
    "fyrestone_combat": 14282752,
    "fyrestone_dynamic": 5705728,
    "fyrestone_p": 28356608,
    "fyrestone_px": 999424,
    "gaiussanctuary_boss": 7614464,
    "gaiussanctuary_catwalk": 1839104,
    "gaiussanctuary_cinematic": 16764928,
    "gaiussanctuary_interactive": 4120576,
    "gaiussanctuary_marcushq": 15335424,
    "gaiussanctuary_missionmain": 19357696,
    "gaiussanctuary_moxxi": 13467648,
    "gaiussanctuary_p": 1789952,
    "gaiussanctuary_reactor": 21979136,
    "gd_assassin_streaming_sf": 2232320,
    "gd_btech_streaming_sf": 2682880,
    "gd_lilac_psycho_streaming_sf": 2646016,
    "gd_mercenary_streaming_sf": 593920,
    "gd_orchid_harpoonhovercraft_sf": 1396736,
    "gd_orchid_hovercraft_sf": 1900544,
    "gd_orchid_rockethovercraft_sf": 1302528,
    "gd_orchid_sawhovercraft_sf": 1417216,
    "gd_runner_streaming_sf": 2490368,
    "gd_sage_corrosivefanboat_sf": 1781760,
    "gd_sage_fanboat_sf": 2523136,
    "gd_sage_incendiaryfanboat_sf": 1957888,
    "gd_sage_shockfanboat_sf": 2408448,
    "gd_siren_streaming_sf": 2465792,
    "gd_soldier_streaming_sf": 1880064,
    "glacial_dynamic": 13205504,
    "glacial_p": 43794432,
    "glacial_px": 71000064,
    "glacial_tundra": 798720,
    "grass_cliffs_combat": 14405632,
    "grass_cliffs_dynamic": 1421312,
    "grass_cliffs_p": 66105344,
    "grass_cliffs_px": 8830976,
    "grass_combat": 8941568,
    "grass_dynamic": 10326016,
    "grass_lynchwood_combat": 9539584,
    "grass_lynchwood_dynamic": 12554240,
    "grass_lynchwood_fx": 868352,
    "grass_lynchwood_p": 42139648,
    "grass_lynchwood_px": 847872,
    "grass_p": 39698432,
    "helios_dahlmine_after": 667648,
    "helios_floor1": 45297664,
    "helios_hangarspaceships": 3182592,
    "helios_interactive": 3874816,
    "helios_landscape": 2666496,
    "helios_lasercontrolroom": 1953792,
    "helios_ld": 8032256,
    "helios_mission_main": 12931072,
    "helios_mission_side": 12918784,
    "helios_moonshotcannon": 2469888,
    "helios_p": 2711552,
    "helios_robotfactory": 2891776,
    "helios_sidea": 7348224,
    "helios_sniperarea": 6025216,
    "helios_uranusarena": 10735616,
    "hunger_boss": 10960896,
    "hunger_dynamic": 4820992,
    "hunger_machinery": 2039808,
    "hunger_mission_1": 10629120,
    "hunger_mission_2": 5382144,
    "hunger_mission_3": 3776512,
    "hunger_mission_intro": 1814528,
    "hunger_p": 45813760,
    "hyperioncity_dynamic": 6975488,
    "hyperioncity_p": 48033792,
    "hyperioncity_px": 3055616,
    "hypinterlude_p": 25206784,
    "ice_dynamic": 24506368,
    "ice_p": 33693696,
    "icecanyon_combat": 11714560,
    "icecanyon_dynamic": 3850240,
    "icecanyon_p": 40255488,
    "icecanyon_px": 663552,
    "interlude_combat": 1974272,
    "interlude_dynamic": 8183808,
    "interlude_p": 44220416,
    "iris_dl1_battle": 6533120,
    "iris_dl1_combat": 2306048,
    "iris_dl1_dynamic": 5136384,
    "iris_dl1_p": 19267584,
    "iris_dl1_skybox": 536576,
    "iris_dl1_tas_combat": 7610368,
    "iris_dl1_tas_dynamic": 2953216,
    "iris_dl1_tas_light": 15245312,
    "iris_dl1_tas_p": 9535488,
    "iris_dl1_tas_skybox": 536576,
    "iris_dl2_combat": 8552448,
    "iris_dl2_interior_combat": 8183808,
    "iris_dl2_interior_dynamic": 4374528,
    "iris_dl2_interior_p": 10211328,
    "iris_dl2_interior_raid": 3600384,
    "iris_dl2_light": 655360,
    "iris_dl2_p": 22331392,
    "iris_dl2_skybox": 1011712,
    "iris_dl3_combat": 15376384,
    "iris_dl3_dynamic": 1421312,
    "iris_dl3_p": 24592384,
    "iris_dl3_skybox": 1269760,
    "iris_hub_combat": 4861952,
    "iris_hub_dynamic": 2232320,
    "iris_hub_p": 4132864,
    "iris_hub_race": 22323200,
    "iris_hub_skybox": 688128,
    "iris_hub2_dynamic": 1486848,
    "iris_hub2_p": 24338432,
    "iris_moxxi_p": 7593984,
    "luckys_dynamic": 7684096,
    "luckys_p": 37478400,
    "luckys_px": 2101248,
    "mines_combat": 5881856,
    "mines_dynamic": 4354048,
    "mines_fx": 806912,
    "mines_mission": 8790016,
    "mines_p": 19345408,
    "mines_px": 1912832,
    "olddust_approach": 29925376,
    "olddust_backburner": 790528,
    "olddust_dahldoorafter": 14659584,
    "olddust_interactive": 1380352,
    "olddust_lair": 3743744,
    "olddust_landscape": 2830336,
    "olddust_ld": 29286400,
    "olddust_mission_main": 20459520,
    "olddust_mission_side": 22917120,
    "olddust_mountain": 16232448,
    "olddust_p": 3837952,
    "olddust_sandwormentrance": 17711104,
    "olddust_skybox": 647168,
    "orchid_caves_combat": 15216640,
    "orchid_caves_dynamic": 1286144,
    "orchid_caves_p": 23060480,
    "orchid_caves_raid_c": 2068480,
    "orchid_caves_raid_p": 1900544,
    "orchid_oasistown_combat": 5349376,
    "orchid_oasistown_dynamic": 12226560,
    "orchid_oasistown_p": 63721472,
    "orchid_oasistown_skybox": 589824,
    "orchid_refinery_combat": 978944,
    "orchid_refinery_dynamic": 585728,
    "orchid_refinery_light": 720896,
    "orchid_refinery_p": 32309248,
    "orchid_refinery_raid": 2551808,
    "orchid_saltflats_combat": 8691712,
    "orchid_saltflats_dynamic": 5095424,
    "orchid_saltflats_p": 47017984,
    "orchid_shipgraveyard_combat": 5902336,
    "orchid_shipgraveyard_dynamic": 5779456,
    "orchid_shipgraveyard_p": 20897792,
    "orchid_shipgraveyard_skybox": 913408,
    "orchid_spire_combat": 2330624,
    "orchid_spire_dynamic": 2854912,
    "orchid_spire_p": 23924736,
    "orchid_spire_skybox": 1380352,
    "orchid_wormbelly_dynamic": 7131136,
    "orchid_wormbelly_p": 14757888,
    "outwash_combat": 24342528,
    "outwash_dam": 11821056,
    "outwash_dynamic": 9809920,
    "outwash_p": 44666880,
    "outwash_px": 4702208,
    "pandorapark_bloodwing": 3178496,
    "pandorapark_combat": 6979584,
    "pandorapark_dynamic": 2334720,
    "pandorapark_p": 58597376,
    "pandorapark_px": 888832,
    "pumpkin_patch_combat": 3772416,
    "pumpkin_patch_dynamic": 9408512,
    "pumpkin_patch_fx": 1409024,
    "pumpkin_patch_p": 26148864,
    "researchcenter_boss": 10805248,
    "researchcenter_dev": 7872512,
    "researchcenter_entrance": 3948544,
    "researchcenter_exterior": 9900032,
    "researchcenter_interactive": 1241088,
    "researchcenter_lift": 876544,
    "researchcenter_missionmain": 15237120,
    "researchcenter_missionside": 5881856,
    "researchcenter_prison": 3469312,
    "researchcenter_research": 20164608,
    "researchcenter_vfx": 1384448,
    "robotslaughter_dynamic": 8167424,
    "robotslaughter_p": 13152256,
    "robotslaughter_skybox": 6131712,
    "sage_cliffs_combat": 8364032,
    "sage_cliffs_dynamic": 2211840,
    "sage_cliffs_p": 20856832,
    "sage_cliffs_raid": 2273280,
    "sage_cliffs_skybox": 671744,
    "sage_hyperionship_dynamic": 8663040,
    "sage_hyperionship_p": 6561792,
    "sage_powerstation_combat": 8286208,
    "sage_powerstation_dynamic": 1818624,
    "sage_powerstation_p": 25137152,
    "sage_powerstation_skybox": 1265664,
    "sage_rockforest_combat": 9658368,
    "sage_rockforest_dynamic": 3420160,
    "sage_rockforest_p": 22048768,
    "sage_underground_combat": 13639680,
    "sage_underground_dynamic": 1142784,
    "sage_underground_p": 26071040,
    "sanctintro_infection": 569344,
    "sanctintro_intro_cinematic": 103768064,
    "sanctintro_missionmain": 3923968,
    "sanctintro_p": 16617472,
    "sanctintro_vfx": 1605632,
    "sanctuary_combat": 1273856,
    "sanctuary_dynamic": 13180928,
    "sanctuary_fx": 856064,
    "sanctuary_hole_p": 44515328,
    "sanctuary_hole_px": 741376,
    "sanctuary_land": 1581056,
    "sanctuary_outer": 847872,
    "sanctuary_p": 15642624,
    "sanctuaryair_combat": 2277376,
    "sanctuaryair_dynamic": 21684224,
    "sanctuaryair_fx": 819200,
    "sanctuaryair_light": 1560576,
    "sanctuaryair_p": 35278848,
    "sanctuaryair_side": 1589248,
    "sandworm_encounters": 10608640,
    "sandworm_interactive": 1019904,
    "sandworm_landscape": 3747840,
    "sandworm_mission_main": 11870208,
    "sandworm_mission_side": 5808128,
    "sandworm_p": 954368,
    "sandworm_tunnel": 3231744,
    "sandworm_zone_01": 6635520,
    "sandworm_zone_02": 786432,
    "sandworm_zone_03": 2703360,
    "sandworm_zone_04": 3969024,
    "sandworm_zone_05": 5001216,
    "sandwormlair_gd": 2715648,
    "sandwormlair_p": 2969600,
    "sandwormlair_terrain": 3272704,
    "southernshelf_dynamic": 13438976,
    "southernshelf_freighter": 1048576,
    "southernshelf_p": 54796288,
    "southernshelf_px": 2027520,
    "southpawfactory_dynamic": 4186112,
    "southpawfactory_p": 21663744,
    "stockade_combat": 35786752,
    "stockade_dynamic": 2265088,
    "stockade_p": 45309952,
    "stockade_px": 1536000,
    "templeslaughter_combat": 17354752,
    "templeslaughter_p": 6512640,
    "testingzone_combat": 26890240,
    "testingzone_dynamic": 1691648,
    "testingzone_p": 22749184,
    "thresherraid_p": 22888448,
    "tundraexpress_combat": 13393920,
    "tundraexpress_dynamic": 8261632,
    "tundraexpress_p": 53420032,
    "tundraexpress_px": 2109440,
    "tundratrain_combat": 1323008,
    "tundratrain_dynamic": 7618560,
    "tundratrain_p": 12771328,
    "village_dynamic": 5918720,
    "village_light": 2220032,
    "village_mission": 11653120,
    "village_p": 12451840,
    "village_px": 4853760,
    "vogchamber_combat": 9502720,
    "vogchamber_dynamic": 10862592,
    "vogchamber_fx": 2297856,
    "vogchamber_p": 8417280,
    "vogchamber_sanctuaryroom": 1617920,
    "xmas_boss": 2932736,
    "xmas_combat": 6176768,
    "xmas_dynamic": 7659520,
    "xmas_mission": 5091328,
    "xmas_p": 35782656,
    "xmas_sidemission": 6406144,
    "xmas_skybox": 1482752,
}
