characters: tuple[str, ...] = (
    "crocus_baroness_streaming_sf",
    "quince_doppel_streaming_sf",
    "gd_enforcer_streaming_sf",
    "gd_gladiator_streaming_sf",
    "gd_lawbringer_streaming_sf",
    "gd_prototype_streaming_sf",
)

levels: tuple[tuple[str, ...], ...] = (
    #fmt: off
    ("GD_Globals.General.LevelList",                       "Helios Station",               "MoonShotIntro_P",     'MoonShotIntro_Audio', 'MoonShotIntro_Dynamic', 'MoonShotIntro_FX', 'MoonShotIntro_Light', 'MoonShotIntro_Skybox', 'MoonShotIntro_Cinematic'),
    ("GD_Globals.General.LevelList",                       "Vorago Solitude",              "Digsite_P",           'Digsite_Two_terrain', 'Digsite_Two_Art', 'Digsite_Audio', 'Digsite_MoonSurface_Sky', 'Digsite_Lighting', 'Digsite_Vista', 'Digsite_SideMissions'),
    ("GD_Globals.General.LevelList",                       "Veins of Helios",              "InnerHull_P",         'InnerHull_Audio', 'InnerHull_Dynamic', 'InnerHull_FX', 'InnerHull_Mission', 'InnerHull_Light', 'InnerHull_Skybox'),
    ("GD_Globals.General.LevelList",                       "Regolith Range",               "Deadsurface_P",       'Deadsurface_Audio', 'Deadsurface_Cinematic', 'Deadsurface_Combat', 'Deadsurface_Dynamic', 'Deadsurface_FX', 'Deadsurface_Light'),
    ("GD_Globals.General.LevelList",                       "Crisis Scar",                  "ComFacility_P",       'ComFacility_Audio', 'ComFacility_Combat', 'ComFacility_Sky', 'ComFacility_Dynamic', 'ComFacility_SideMissions'),
    ("GD_Globals.General.LevelList",                       "Tycho's Ribs",                 "Access_P",            '11B_Access_ART', '11B_Access_ART_AltarRoom', '11B_Access_ART_Catacombs', '11B_Access_ART_EridianTowers', '11B_Access_ART_fx', '11B_Access_ART_organic', '11B_Access_ART_ShieldArea', '11B_Access_ART_StartRoom', '11B_Access_Challenges', '11B_Access_GAME', '11B_Access_MoonSurface_Sky', '11B_Elevator_Light', '11B_Facility_A_Combat', 'Access_LootA', 'Access_Audio'),
    ("GD_Globals.General.LevelList",                       "Lunar Launching Station",      "Laser_P",             'Laser_Audio', 'Laser_Dynamic', 'Laser_FX', 'Laser_Mission'),
    ("GD_Globals.General.LevelList",                       "Sub-Level 13",                 "Sublevel13_P",        'Sublevel13_Combat', 'Sublevel13_Dynamic', 'Sublevel13_Geometry'),
    ("GD_Globals.General.LevelList",                       "Outfall Pumping Station",      "Digsite_Rk5arena_P",  'Digsite_Dynamic', 'Digsite_Rk5battle', 'Digsite_Rk5arena_Art', 'Digsite_Rk5arena_Lighting', 'Digsite_Rk5arena_Terrain', 'Digsite_Rk5arena_Audio', 'Digsite_Rk5arena_Sky', 'Digsite_Rk5arena_Vista'),
    ("GD_Globals.General.LevelList",                       "Eleseer",                      "InnerCore_p",         'InnerCore_lighting', 'InnerCore_Art', 'InnerCore_Audio', 'InnerCore_geo_01', 'InnerCore_combat00', 'InnerCore_loot00', 'InnerCore_FX', 'InnerCore_OPHATitleCard', 'InnerCore_challenges', 'InnerCore_geo_02', 'Vault_WorldGeo', 'Vault_Boss', 'Vault_Mission'),
    ("GD_Globals.General.LevelList",                       "The Meriff's Office",          "Meriff_P",            'Meriff_Town', 'Meriff_Lights', 'Meriff_M_Chp4', 'Meriff_sky', 'Meriff_Audio', 'Meriff_SideMissions'),
    ("GD_Globals.General.LevelList",                       "Stanton's Liver",              "StantonsLiver_P",     'StantonsLiver_Audio', 'StantonsLiver_Dynamic', 'StantonsLiver_Combat', 'StantonsLiver_SkyDynamic', 'StantonsLiver_SideMissions'),
    ("GD_Globals.General.LevelList",                       "Research and Development",     "RandDFacility_P",     'RandDFacility_Audio', 'RandDFacility_Dynamic', 'RandDFacility_FX', 'RandDFacility_Light', 'RandDFacility_Mission', 'RandDFacility_Skybox'),
    ("GD_Globals.General.LevelList",                       "Outlands Canyon",              "Outlands_P2",         'Outlands_Audio2', 'Outlands_Sky2', 'Outlands_Combat2', 'Outlands_SideMissions2'),
    ("GD_Globals.General.LevelList",                       "Concordia",                    "Spaceport_P",         'Spaceport_Audio', 'Spaceport_Dynamic', 'Spaceport_Town', 'Spaceport_Vista', 'Spaceport_Combat', 'Spaceport_SideMissions', 'Spaceport_M_Chp3', 'Spaceport_M_Chp4', 'Spaceport_Sky', 'Spaceport_Lights'),
    ("GD_Globals.General.LevelList",                       "Outlands Spur",                "Outlands_P",          'Outlands_Combat', 'Outlands_Audio', 'Outlands_SideMissions', 'Outlands_Sky'),
    ("GD_Globals.General.LevelList",                       "Titan Robot Production Plant", "DahlFactory_Boss",    'DahlFactory_BossCombat', 'DahlFactory_BotF', 'DahlFactory_BossDynamic', 'DahlFactory_Boss_Audio'),
    ("GD_Globals.General.LevelList",                       "Eye of Helios",                "LaserBoss_P",         'LaserBoss_Audio', 'LaserBoss_Dynamic', 'LaserBoss_FX', 'LaserBoss_Mission', 'LaserBoss_Light', 'LaserBoss_Skybox', 'LaserBoss_Cinematic', 'LaserBoss_Boss'),
    ("GD_Globals.General.LevelList",                       "Jack's Office",                "JacksOffice_P",       'JacksOffice_Audio', 'JacksOffice_Dynamic', 'JacksOffice_FX', 'JacksOffice_Light', 'JacksOffice_Mission', 'JacksOffice_Skybox', 'JacksOffice_Cinematic'),
    ("GD_Globals.General.LevelList",                       "Triton Flats",                 "Moon_P",              'Moon_Combat', 'Moon_Dynamic', 'Moon_Audio', 'Moon_SideMissions', 'Moon_SkyDynamic'),
    ("GD_Globals.General.LevelList",                       "Pity's Fall",                  "Wreck_P",             'Wreck_Int1', 'Wreck_Combat', 'Wreck_Combat2', 'Wreck_Dynamic', 'Wreck_Sky', 'Wreck_SideMissions', 'Wreck_Audio'),
    ("GD_Globals.General.LevelList",                       "Hyperion Hub of Heroism",      "centralterminal_p",   'CentralTerminal_Audio', 'CentralTerminal_Dynamic', 'CentralTerminal_FX', 'CentralTerminal_Missions', 'CentralTerminal_Lights', 'CentralTerminal_Skybox'),
    ("GD_Globals.General.LevelList",                       "Titan Industrial Facility",    "DahlFactory_P",       'DahlFactory_StingrayF', 'DahlFactory_TStation', 'DahlFactory_Combat', 'DahlFactory_Dynamic', 'DahlFactory_Sky', 'DahlFactory_FX', 'DahlFactory_Vista', 'DahlFactory_Audio'),
    ("GD_Globals.General.LevelList",                       "Serenity's Waste",             "Moonsurface_P",       'Moonsurface_Audio', 'Moonsurface_Combat', 'Moonsurface_Dynamic', 'Moonsurface_FX', 'Moonsurface_Light', 'Moonsurface_Cinematic'),
    ("GD_FreesiaPackageDef.LevelList_Freesia",             "Abandoned Training Facility",  "MoonSlaughter_P",     'MoonSlaughter_Combat', 'MoonSlaughter_Audio', 'MoonSlaughter_Sky'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Subconscious",                 "Ma_Subconscious_P",   'Ma_Subconscious_Sky', 'Ma_Subconscious_Game', 'Ma_Subconscious_SideMissions', 'Ma_Subconscious_Audio', 'Ma_Subconscious_NotStreamed'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Motherlessboard",              "Ma_Motherboard_P",    'Ma_Motherboard_Gply', 'Ma_Motherboard_Audio', 'Ma_Motherboard_Side'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Deck 13.5",                    "Ma_FinalBoss_P",      'Ma_FinalBoss_Audio', 'Ma_FinalBoss_Geo', 'Ma_FinalBoss_Game', 'Ma_FinalBoss_ThroneRoom'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Cluster 99002 0V3RL00K",       "Ma_RightCluster_P",   'Ma_RightCluster_Combat', 'Ma_RightCluster_SideMission', 'Ma_RightCluster_Audio', 'Ma_RightCluster_Corruption'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "The Cortex",                   "Ma_SubBoss_P",        'Ma_SubBoss_Mutator', 'Ma_SubBoss_Geo', 'Ma_SubBoss_Game', 'Ma_SubBoss_Audio', 'Ma_SubBoss_Drill'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "The Nexus",                    "Ma_Nexus_P",          'Ma_Nexus_Art', 'Ma_Nexus_Gply', 'Ma_Nexus_Sky', 'Ma_Nexus_Audio', 'Ma_Nexus_Side', 'Ma_Nexus_Cinematics', 'Ma_Nexus_PCFX'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Deck 13 ½",                    "Ma_Deck13_P",         'MA_DECK13_AUDIO', 'Ma_Deck13_Intro_SS', 'Ma_Deck13_Game', 'Ma_Deck13_TargetRange'),
    ("GD_MarigoldPackageDef.LevelList.Marigold_LevelList", "Cluster 00773 P4ND0R4",        "Ma_LeftCluster_P",    'Ma_LeftCluster_Combat', 'Ma_LeftCluster_Dynamic', 'Ma_LeftCluster_PC_FX', 'Ma_LeftCluster_SideMissions', 'Ma_LeftCluster_Audio'),
    ("GD_PetuniaPackageDef.LevelList.Petunia_LevelList",   "The Holodome",                 "Eridian_slaughter_P", 'ERIDIAN_SLAUGHTER_ART', 'Eridian_slaughter_Lighting', 'Eridian_slaughter_Combat', 'ERIDIAN_SLAUGHTER_AUDIO', 'Eridian_slaughter_Audio2', 'Eridian_slaughter_Scripting'),
    #fmt: on
)

package_sizes: dict[str, int] = {
    "11b_access_game": 7512064,
    "11b_facility_a_combat": 6348800,
    "access_p": 38273024,
    "centralterminal_dynamic": 8556544,
    "centralterminal_lights": 3366912,
    "centralterminal_missions": 15626240,
    "centralterminal_p": 54022144,
    "comfacility_combat": 10309632,
    "comfacility_dynamic": 6377472,
    "comfacility_p": 45625344,
    "comfacility_sidemissions": 3215360,
    "crocus_baroness_streaming_sf": 4567040,
    "dahlfactory_boss": 2195456,
    "dahlfactory_bosscombat": 14897152,
    "dahlfactory_bossdynamic": 16236544,
    "dahlfactory_botf": 15822848,
    "dahlfactory_combat": 10510336,
    "dahlfactory_dynamic": 11362304,
    "dahlfactory_p": 6393856,
    "dahlfactory_stingrayf": 13750272,
    "dahlfactory_tstation": 6156288,
    "deadsurface_combat": 5316608,
    "deadsurface_dynamic": 10633216,
    "deadsurface_p": 45965312,
    "digsite_lighting": 2748416,
    "digsite_p": 20500480,
    "digsite_rk5arena_audio": 1069056,
    "digsite_rk5arena_p": 3563520,
    "digsite_rk5arena_terrain": 1449984,
    "digsite_rk5battle": 8323072,
    "digsite_sidemissions": 6995968,
    "digsite_two_art": 6365184,
    "digsite_two_terrain": 1142784,
    "digsite_vista": 532480,
    "eridian_slaughter_art": 30474240,
    "eridian_slaughter_combat": 32374784,
    "eridian_slaughter_p": 7335936,
    "eridian_slaughter_scripting": 24117248,
    "gd_co_stingray_streaming_sf": 2838528,
    "gd_enforcer_streaming_sf": 2514944,
    "gd_gladiator_streaming_sf": 1548288,
    "gd_lawbringer_streaming_sf": 2629632,
    "gd_moonbuggy_streaming_sf": 3002368,
    "innercore_art": 2498560,
    "innercore_audio": 950272,
    "innercore_combat00": 4354048,
    "innercore_geo_02": 1302528,
    "innercore_ophatitlecard": 2912256,
    "innercore_p": 2093056,
    "innercore_sky": 1064960,
    "innerhull_combat": 7671808,
    "innerhull_dynamic": 4669440,
    "innerhull_mission": 6316032,
    "innerhull_p": 31346688,
    "jacksoffice_mission": 7712768,
    "jacksoffice_p": 8491008,
    "laser_dynamic": 5222400,
    "laser_fx": 1503232,
    "laser_mission": 14557184,
    "laser_p": 22175744,
    "laserboss_boss": 7548928,
    "laserboss_cinematic": 6234112,
    "laserboss_mission": 12177408,
    "laserboss_p": 16117760,
    "ma_deck13_game": 65941504,
    "ma_deck13_intro_ss": 5718016,
    "ma_deck13_p": 56156160,
    "ma_deck13_targetrange": 1843200,
    "ma_finalboss_game": 35278848,
    "ma_finalboss_geo": 5844992,
    "ma_finalboss_p": 5758976,
    "ma_finalboss_throneroom": 10534912,
    "ma_leftcluster_combat": 23621632,
    "ma_leftcluster_dynamic": 13447168,
    "ma_leftcluster_p": 52363264,
    "ma_leftcluster_pc_fx": 577536,
    "ma_leftcluster_sidemissions": 7012352,
    "ma_motherboard_gply": 18935808,
    "ma_motherboard_p": 31760384,
    "ma_motherboard_side": 2756608,
    "ma_nexus_art": 13746176,
    "ma_nexus_cinematics": 4222976,
    "ma_nexus_gply": 24436736,
    "ma_nexus_p": 11395072,
    "ma_nexus_side": 17682432,
    "ma_nexus_sky": 1077248,
    "ma_rightcluster_combat": 51834880,
    "ma_rightcluster_corruption": 6037504,
    "ma_rightcluster_p": 134172672,
    "ma_rightcluster_sidemission": 8183808,
    "ma_subboss_drill": 39444480,
    "ma_subboss_game": 41533440,
    "ma_subboss_geo": 58212352,
    "ma_subboss_mutator": 13881344,
    "ma_subconscious_game": 22138880,
    "ma_subconscious_p": 48443392,
    "ma_subconscious_sidemissions": 15740928,
    "meriff_m_chp4": 8978432,
    "meriff_sidemissions": 1978368,
    "meriff_sky": 720896,
    "meriff_town": 26800128,
    "moon_combat": 4665344,
    "moon_dynamic": 5111808,
    "moon_p": 37609472,
    "moon_sidemissions": 10866688,
    "moonshotintro_cinematic": 6512640,
    "moonshotintro_dynamic": 13496320,
    "moonshotintro_p": 24891392,
    "moonshotintro_skybox": 532480,
    "moonslaughter_combat": 4055040,
    "moonslaughter_p": 14594048,
    "moonsurface_combat": 1093632,
    "moonsurface_dynamic": 10358784,
    "moonsurface_p": 26259456,
    "outlands_combat": 1650688,
    "outlands_combat2": 14647296,
    "outlands_p": 43630592,
    "outlands_p2": 16658432,
    "outlands_sidemissions": 774144,
    "outlands_sidemissions2": 11460608,
    "quince_doppel_streaming_sf": 1933312,
    "randdfacility_dynamic": 5926912,
    "randdfacility_mission": 22511616,
    "randdfacility_p": 31170560,
    "spaceport_combat": 5476352,
    "spaceport_dynamic": 1216512,
    "spaceport_m_chp3": 716800,
    "spaceport_m_chp4": 1085440,
    "spaceport_p": 11505664,
    "spaceport_sidemissions": 4534272,
    "spaceport_town": 13324288,
    "stantonsliver_combat": 4726784,
    "stantonsliver_dynamic": 1097728,
    "stantonsliver_p": 24875008,
    "sublevel13_combat": 5132288,
    "sublevel13_dynamic": 3256320,
    "sublevel13_geometry": 16838656,
    "sublevel13_p": 663552,
    "vault_boss": 7385088,
    "vault_cinematic": 1933312,
    "vault_mission": 2666496,
    "vault_worldgeo": 1134592,
    "wreck_combat": 17866752,
    "wreck_combat2": 11128832,
    "wreck_dynamic": 8802304,
    "wreck_int1": 24797184,
    "wreck_sidemissions": 4055040,
}
